### ISSUE TITLE
v4.1.0.4 Exception log crash

### ISSUE THREAD

**Issue by Vitae666** [monsenanna/CQAutomater#6]
[ExceptionLog.txt](https://github.com/monsenanna/CQAutomater/files/2825767/ExceptionLog.txt)

2/3/2019 7:31:06 AM
System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at CQFollowerAutoclaimer.PFStuff.<getWBData>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CQFollowerAutoclaimer.AutoWB.<WBTimer_Elapsed>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by monsenanna** [comment]
This is due to CQ server issues, and should be resolved once the game server is fixed.

**Comment by Vitae666** [comment]
Yeah, just found out from Ayla with DQ not working.
Speaking of DQ, ever going to have the Automater actually run the DQ's
automatically rather than wait for the button press to start the process?

**Comment by monsenanna** [comment]
Yea, thats the next bug I'm working on.
